-- ==================================================================
-- Author:          Piotr Lasek
-- Create date:     June 3, 2016
-- Description:     Loads data and transforms data into an appropriate
--                  format.
-- ==================================================================

TODO: FILE TO BE DELETED!


-- HISTORY
-- 4.05.2017
--            Columns names have to be fixed in all years from 2009 until 2015 and data has to be imported again!!!

\timing on

\i 0-clear-db.sql

\i create-data-in.sql

-- Copying data
-- ------------------------------------------------------------------
-- \i copy-data.sql

-- Changing types of columns.
-- ------------------------------------------------------------------

\timing on

DROP TABLE IF EXISTS DATA_IN_ALL;

CREATE TABLE DATA_IN_ALL (
  VENDOR_ID VARCHAR(5),
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PICKUP_DATETIME TIMESTAMP,
  DROPOFF_DATETIME TIMESTAMP,
  TRIP_DISTANCE FLOAT, 
  FARE_AMOUNT FLOAT,
  SURCHARGE FLOAT,
  MTA_TAX FLOAT,
  TOLLS_AMOUNT FLOAT,
  TOTAL_AMOUNT FLOAT,
  PASSENGER_COUNT INTEGER,
  RATE_CODE INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5)
);

-- CASE WHEN TRIP_TIME_IN_SECS~E'^\\d+$' THEN TRIP_TIME_IN_SECS::INTEGER ELSE 0 END AS TRIP_TIME_IN_SECS,
  
INSERT INTO DATA_IN_ALL
	SELECT
	  VENDOR_ID,
	  CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE,
	  CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE,
	  CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE,
	  CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE,
	  CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME,
	  CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME,
	  CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE,
	  CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN FARE_AMOUNT::FLOAT ELSE 0 END AS FARE_AMOUNT,
	  CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN SURCHARGE::FLOAT ELSE 0 END AS SURCHARGE,
	  CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN MTA_TAX::FLOAT ELSE 0 END AS MTA_TAX,
	  CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TOLLS_AMOUNT::FLOAT ELSE 0 END AS TOLLS_AMOUNT,
	  CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TOTAL_AMOUNT::FLOAT ELSE 0 END AS TOTAL_AMOUNT,
	  CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT,
	  CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE,
	  -- CASE WHEN TRIP_TIME_IN_SECS~E'^\\d+$' THEN TRIP_TIME_IN_SECS::INTEGER ELSE 0 END AS TRIP_TIME_IN_SECS,
	  STORE_AND_FWD_FLAG
	FROM
	  DATA_IN_2009;

-- 12249209 ms -> 170896055
INSERT INTO DATA_IN_ALL SELECT VENDOR_ID, CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE, CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE, CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE, CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE, CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME, CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME, CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE, CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS FARE_AMOUNT, CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS SURCHARGE, CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS MTA_TAX, CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOLLS_AMOUNT, CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOTAL_AMOUNT, CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT, CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE, STORE_AND_FWD_FLAG FROM DATA_IN_2010;
-- 11664817 ms -> 144971391
INSERT INTO DATA_IN_ALL SELECT VENDOR_ID, CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE, CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE, CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE, CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE, CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME, CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME, CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE, CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS FARE_AMOUNT, CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS SURCHARGE, CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS MTA_TAX, CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOLLS_AMOUNT, CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOTAL_AMOUNT, CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT, CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE, STORE_AND_FWD_FLAG FROM DATA_IN_2011;
-- 14219293 ms -> 176897199
INSERT INTO DATA_IN_ALL SELECT VENDOR_ID, CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE, CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE, CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE, CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE, CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME, CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME, CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE, CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS FARE_AMOUNT, CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS SURCHARGE, CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS MTA_TAX, CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOLLS_AMOUNT, CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOTAL_AMOUNT, CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT, CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE, STORE_AND_FWD_FLAG FROM DATA_IN_2012;
--             -> 163847741
INSERT INTO DATA_IN_ALL SELECT VENDOR_ID, CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE, CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE, CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE, CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE, CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME, CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME, CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE, CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS FARE_AMOUNT, CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS SURCHARGE, CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS MTA_TAX, CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOLLS_AMOUNT, CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOTAL_AMOUNT, CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT, CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE, STORE_AND_FWD_FLAG FROM DATA_IN_2013;
-- 13759827 ms -> 173179759
INSERT INTO DATA_IN_ALL SELECT VENDOR_ID, CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE, CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE, CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE, CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE, CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME, CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME, CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE, CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS FARE_AMOUNT, CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS SURCHARGE, CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS MTA_TAX, CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOLLS_AMOUNT, CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOTAL_AMOUNT, CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT, CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE, STORE_AND_FWD_FLAG FROM DATA_IN_2014;
-- 13116042 ms -> 165114361
INSERT INTO DATA_IN_ALL SELECT VENDOR_ID, CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE, CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE, CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE, CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE, CASE WHEN PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME, CASE WHEN DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME, CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE, CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS FARE_AMOUNT, CASE WHEN SURCHARGE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS SURCHARGE, CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS MTA_TAX, CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOLLS_AMOUNT, CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TOTAL_AMOUNT, CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT, CASE WHEN RATE_CODE~E'^\\d+$' THEN RATE_CODE::INTEGER ELSE  -1 END AS RATE_CODE, STORE_AND_FWD_FLAG FROM DATA_IN_2015;
-- 11500970 ms -> 146112977

-- Creating indexes
-- ------------------------------------------------------------------

CREATE INDEX ON DATA_IN_ALL(PICKUP_DATETIME);
CREATE INDEX ON DATA_IN_ALL(DROPOFF_DATETIME);
CREATE INDEX ON DATA_IN_ALL(PICKUP_LONGITUDE); -- 16371437 ms -> 4.5 h
CREATE INDEX ON DATA_IN_ALL(PICKUP_LATITUDE);
CREATE INDEX ON DATA_IN_ALL(DROPOFF_LONGITUDE);
CREATE INDEX ON DATA_IN_ALL(DROPOFF_LATITUDE);

ALTER TABLE DATA_IN_ALL ADD COLUMN TRIP_TIME_SEC INTEGER;
UPDATE DATA_IN_ALL SET TRIP_TIME_SEC = EXTRACT(EPOCH FROM (DROPOFF_DATETIME - PICKUP_DATETIME))::INTEGER WHERE DROPOFF_DATETIME > '2000-01-01' AND DROPOFF_DATETIME >= PICKUP_DATETIME;

UPDATE
    DATA_IN_ALL
SET
    TRIP_TIME_SEC =
        EXTRACT(EPOCH FROM (DROPOFF_DATETIME - PICKUP_DATETIME))::INTEGER
WHERE
    DROPOFF_DATETIME > '2000-01-01' AND
    DROPOFF_DATETIME >= PICKUP_DATETIME;


	
CREATE TABLE
  DATA_IN_ALL
AS SELECT
  VENDORID,
  CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE,
  CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE,
  CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE,
  CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE,
  CASE WHEN TPEP_PICKUP_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(TPEP_PICKUP_DATETIME, 'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME,
  CASE WHEN TPEP_DROPOFF_DATETIME~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(TPEP_DROPOFF_DATETIME, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME,
  CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE,
  CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN FARE_AMOUNT::FLOAT ELSE 0 END AS FARE_AMOUNT,
  CASE WHEN EXTRA~E'^\\d*\\.\\d*' THEN EXTRA::FLOAT ELSE 0 END AS SURCHARGE,
  CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN MTA_TAX::FLOAT ELSE 0 END AS MTA_TAX,
  CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TOLLS_AMOUNT::FLOAT ELSE 0 END AS TOLLS_AMOUNT,
  CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TOTAL_AMOUNT::FLOAT ELSE 0 END AS TOTAL_AMOUNT,
  CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT,
  CASE WHEN RATECODEID~E'^\\d+$' THEN RATECODEID::INTEGER ELSE  -1 END AS RATE_CODE,
  -- CASE WHEN TRIP_TIME_IN_SECS~E'^\\d+$' THEN TRIP_TIME_IN_SECS::INTEGER ELSE 0 END AS TRIP_TIME_IN_SECS,
  STORE_AND_FWD_FLAG
FROM
  DATA_IN_2016;
  
ALTER TABLE DATA_IN_ALL ADD COLUMN TRIP_TIME_IN_SECS INT;
UPDATE DATA_IN_ALL SET TRIP_TIME_IN_SECS = EXTRACT(EPOCH FROM DROPOFF_DATETIME - PICKUP_DATETIME);
CREATE TABLE DATA AS SELECT * FROM DATA_IN_ALL;


