\timing on

DROP TABLE IF EXISTS DATA_IN_2015;

CREATE TABLE DATA_IN_2015 (
    VENDORID TEXT, 
    TPEP_PICKUP_DATETIME TEXT, 
    TPEP_DROPOFF_DATETIME TEXT, 
    PASSENGER_COUNT TEXT, 
    TRIP_DISTANCE TEXT, 
    PICKUP_LONGITUDE TEXT, 
    PICKUP_LATITUDE TEXT, 
    RATECODEID TEXT, 
    STORE_AND_FWD_FLAG TEXT, 
    DROPOFF_LONGITUDE TEXT, 
    DROPOFF_LATITUDE TEXT, 
    PAYMENT_TYPE TEXT, 
    FARE_AMOUNT TEXT, 
    EXTRA TEXT, 
    MTA_TAX TEXT, 
    TIP_AMOUNT TEXT, 
    TOLLS_AMOUNT TEXT, 
    IMPROVEMENT_SURCHARGE TEXT, 
    TOTAL_AMOUNT TEXT             
    );

\copy data_in_2015 from '/home/piotr/nytc/yt_2015-01.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-02.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-03.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-04.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-05.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-06.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-07.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-08.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-09.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-10.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-11.csv' DELIMITER ',' CSV HEADER
\copy data_in_2015 from '/home/piotr/nytc/yt_2015-12.csv' DELIMITER ',' CSV HEADER

INSERT INTO DATA_IN_ALL
SELECT
	VENDORID,
	CASE WHEN PICKUP_LONGITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LONGITUDE::FLOAT ELSE 0 END AS PICKUP_LONGITUDE,
	CASE WHEN PICKUP_LATITUDE~E'^-?\\d*\\.\\d*' THEN PICKUP_LATITUDE::FLOAT ELSE 0 END AS PICKUP_LATITUDE,
	CASE WHEN DROPOFF_LONGITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LONGITUDE::FLOAT ELSE 0 END AS DROPOFF_LONGITUDE,
	CASE WHEN DROPOFF_LATITUDE~E'^-?\\d*\\.\\d*' THEN DROPOFF_LATITUDE::FLOAT ELSE 0 END AS DROPOFF_LATITUDE,
	CASE WHEN tpep_pickup_datetime~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(tpep_pickup_datetime,	'yyyy-mm-dd HH24:MI:SS') ELSE NULL END AS PICKUP_DATETIME,
	CASE WHEN tpep_dropoff_datetime~E'^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' THEN TO_TIMESTAMP(tpep_dropoff_datetime, 'yyyy-mm-dd HH24:MI:SS')  ELSE NULL END AS DROPOFF_DATETIME,
	CASE WHEN TRIP_DISTANCE~E'^\\d*\\.\\d*' THEN TRIP_DISTANCE::FLOAT ELSE 0 END AS TRIP_DISTANCE,
	CASE WHEN FARE_AMOUNT~E'^\\d*\\.\\d*' THEN FARE_AMOUNT::FLOAT ELSE 0 END AS FARE_AMOUNT,
	CASE WHEN extra~E'^\\d*\\.\\d*' THEN extra::FLOAT ELSE 0 END AS SURCHARGE,
	CASE WHEN MTA_TAX~E'^\\d*\\.\\d*' THEN MTA_TAX::FLOAT ELSE 0 END AS MTA_TAX,
	CASE WHEN TOLLS_AMOUNT~E'^\\d*\\.\\d*' THEN TOLLS_AMOUNT::FLOAT ELSE 0 END AS TOLLS_AMOUNT,
	CASE WHEN TOTAL_AMOUNT~E'^\\d*\\.\\d*' THEN TOTAL_AMOUNT::FLOAT ELSE 0 END AS TOTAL_AMOUNT,
	CASE WHEN PASSENGER_COUNT~E'^\\d+$'  THEN PASSENGER_COUNT::INTEGER ELSE 0 END AS PASSENGER_COUNT,
	CASE WHEN ratecodeid~E'^\\d+$' THEN ratecodeid::INTEGER ELSE  -1 END AS RATE_CODE,
	STORE_AND_FWD_FLAG
FROM DATA_IN_2015;
