DROP TABLE CUBED_PYRAMID CASCADE;

/*
 * Initialize pyramid by removing "duplicates".
 */

CREATE TABLE CUBED_PYRAMID AS
SELECT
      0 AS SPACE_LAYER, -- This is not a base space layer
      0 AS TIME_LAYER, -- This is not a base time layer
      CAST((LONGITUDE - (SELECT MIN(LONGITUDE) FROM CHECKINS))* 1000000000 AS BIGINT) AS TILE_X,
      CAST((LATITUDE - (SELECT MIN(LATITUDE) FROM CHECKINS)) * 1000000000 AS BIGINT) AS TILE_Y,
      S AS TIME,
      COUNT(USER_ID) AS CNT
   FROM
      CH2 -- checkins table with auxiliary column S -- seconds
   GROUP BY
      LONGITUDE,
      LATITUDE,
      S -- TIME
   WITH DATA;

-- ------------------------------------------------------------------------------------------

-- LAYER 1
SELECT CREATE_BASE_LAYER(); -- 15 seconds
SELECT CREATE_TIME_LAYER(1, 2);
SELECT CREATE_TIME_LAYER(1, 3);
SELECT CREATE_TIME_LAYER(1, 4);
SELECT CREATE_TIME_LAYER(1, 5);
SELECT CREATE_TIME_LAYER(1, 6);
SELECT CREATE_TIME_LAYER(1, 7);
SELECT CREATE_TIME_LAYER(1, 8);
SELECT CREATE_TIME_LAYER(1, 9);
SELECT CREATE_TIME_LAYER(1, 10);
SELECT CREATE_TIME_LAYER(1, 11);
SELECT CREATE_TIME_LAYER(1, 12);
SELECT CREATE_TIME_LAYER(1, 13);
SELECT CREATE_TIME_LAYER(1, 14);

-- LAYER 2
SELECT CREATE_SPACE_LAYER(2);
SELECT CREATE_TIME_LAYER(2, 2);
SELECT CREATE_TIME_LAYER(2, 3);
SELECT CREATE_TIME_LAYER(2, 4);
SELECT CREATE_TIME_LAYER(2, 5);
SELECT CREATE_TIME_LAYER(2, 6);
SELECT CREATE_TIME_LAYER(2, 7);
SELECT CREATE_TIME_LAYER(2, 8);
SELECT CREATE_TIME_LAYER(2, 9);

-- LAYER 3
SELECT CREATE_SPACE_LAYER(3);
SELECT CREATE_TIME_LAYER(3, 2);
SELECT CREATE_TIME_LAYER(3, 3);
SELECT CREATE_TIME_LAYER(3, 4);
SELECT CREATE_TIME_LAYER(3, 5);
SELECT CREATE_TIME_LAYER(3, 6);
SELECT CREATE_TIME_LAYER(3, 7);

-- LAYER 4
SELECT CREATE_SPACE_LAYER(4);
SELECT CREATE_TIME_LAYER(4, 2);
SELECT CREATE_TIME_LAYER(4, 3);
SELECT CREATE_TIME_LAYER(4, 4);
SELECT CREATE_TIME_LAYER(4, 5);
SELECT CREATE_TIME_LAYER(4, 6);
SELECT CREATE_TIME_LAYER(4, 7);
SELECT CREATE_TIME_LAYER(4, 8);
SELECT CREATE_TIME_LAYER(4, 9);
SELECT CREATE_TIME_LAYER(4, 10);

-- LAYER 5
SELECT CREATE_SPACE_LAYER(5);
SELECT CREATE_TIME_LAYER(5, 2);
SELECT CREATE_TIME_LAYER(5, 3);
SELECT CREATE_TIME_LAYER(5, 4);
SELECT CREATE_TIME_LAYER(5, 5);


-- LAYER 6
SELECT CREATE_SPACE_LAYER(6);
SELECT CREATE_TIME_LAYER(6, 2);
SELECT CREATE_TIME_LAYER(6, 3);
SELECT CREATE_TIME_LAYER(6, 4);
SELECT CREATE_TIME_LAYER(6, 5);
